[package]
name = "cypher_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.0"
chumsky = { version = "0.9.3", default-features = false, features = ["std"] }
internment = "0.7.4"
